// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeJJpXlRxarH6Tpy8IAdx3kTDN6TZHT2Q',
    appId: '1:693043234789:web:4f7af711630102da2c110c',
    messagingSenderId: '693043234789',
    projectId: 'login-page-21068',
    authDomain: 'login-page-21068.firebaseapp.com',
    storageBucket: 'login-page-21068.firebasestorage.app',
    measurementId: 'G-Q4TDZL1ZCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFsIJZe_lGF0WF9K2XAdRWop4LaWSbnFA',
    appId: '1:693043234789:android:92419deca97b93432c110c',
    messagingSenderId: '693043234789',
    projectId: 'login-page-21068',
    storageBucket: 'login-page-21068.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV53FS07hmLHXz1XLBbawb_nXOoZGZoS4',
    appId: '1:693043234789:ios:f47758eab43360832c110c',
    messagingSenderId: '693043234789',
    projectId: 'login-page-21068',
    storageBucket: 'login-page-21068.firebasestorage.app',
    iosClientId: '693043234789-cctscq49db4802o5vno87vj3qsd5hma9.apps.googleusercontent.com',
    iosBundleId: 'com.example.medremm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV53FS07hmLHXz1XLBbawb_nXOoZGZoS4',
    appId: '1:693043234789:ios:f47758eab43360832c110c',
    messagingSenderId: '693043234789',
    projectId: 'login-page-21068',
    storageBucket: 'login-page-21068.firebasestorage.app',
    iosClientId: '693043234789-cctscq49db4802o5vno87vj3qsd5hma9.apps.googleusercontent.com',
    iosBundleId: 'com.example.medremm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeJJpXlRxarH6Tpy8IAdx3kTDN6TZHT2Q',
    appId: '1:693043234789:web:4c93ba7803db984d2c110c',
    messagingSenderId: '693043234789',
    projectId: 'login-page-21068',
    authDomain: 'login-page-21068.firebaseapp.com',
    storageBucket: 'login-page-21068.firebasestorage.app',
    measurementId: 'G-Z28WVBJKC9',
  );
}
